import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/stores/storeProvider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider >
      <html lang="en">
        <body className={`${inter.className} ${poppins.className}`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
